#!/bin/bash

case $BUTTON in
	1) notify-send " Brightness module" "\- Shows screen brightness.
- Mouse wheel: adjust brightness." ;;
    4) xbacklight -inc 5 ;;
	5) xbacklight -dec 5 ;;
esac

brightness="$(xbacklight -get | awk -F. '{print $1}')"

echo "^C11^^B0^[ $brightness%]^d^"
