#!/bin/bash

for battery in /sys/class/power_supply/BAT?*; do
    [ -n "${capacity+x}" ] && printf " "


#battery=$(cat /sys/class/power_supply/BAT0/status)
#plugged=""

    case "$(cat "$battery/status" 2>&1)" in
	    "Full") status="⚡" ;;
	    "Discharging")
		    if [ "$capacity" -gt "75" ]; then
			    status="🔋"
    		elif [ "$capacity" -gt "50" ]; then
    			status=""
    		elif [ "$capacity" -gt "25" ]; then
    			status=""
    		elif [ "$capacity" -gt "10" ]; then
    			status=""
    		else
    			status=""
    		fi ;;
    	"Charging")
            status="🔌" ;;
    	"Not charging") status="" ;;
    	"Unknown") status="" ;;
    	*) exit 1 ;;
    esac
    capacity="$(cat "$battery/capacity" 2>&1)"

#if [ "$capacity" -gt "60" ]; then
#    echo "^C2^^B0^[$status $capacity%]^d^"
#elif [ "$capacity" -gt "30" ]; then
#    echo "^C3^^B0^[$status $capacity%]^d^"
#else
#    echo "^C1^^B0^[$status $capacity%]^d^"
#fi

echo "^C14^^B13^^C0^^B14^ $status $capacity% ^d^"
