#!/bin/bash

[ $(pamixer --get-mute) = true ] && echo " muted" && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "50" ]; then
	icon="🔊 "
elif [ "$vol" -gt "0" ]; then
	icon="🔈 "
else
        echo " muted" && exit
fi

echo "^C6^^B5^^B6^ ^C0^^B6^$icon$vol% ^d^"
