#!/bin/bash

case $BUTTON in
	1) notify-send "🔊 Volume module " "\- Shows speakers volume.
- Mouse wheel: adjust volume." ;;
    4) pactl set-sink-mute @DEFAULT_SINK@ false && pactl set-sink-volume @DEFAULT_SINK@ +5% ;;
    5) pactl set-sink-mute @DEFAULT_SINK@ false && pactl set-sink-volume @DEFAULT_SINK@ -5% ;;
esac

[ $(pamixer --get-mute) = true ] && echo "^C6^^B0^[ muted]^d^" && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "50" ]; then
	icon="🔊 "
elif [ "$vol" -gt "0" ]; then
	icon="🔈 "
else
        echo "^C6^^B0^[ muted]^d^" && exit
fi

echo "^C6^^B0^[$icon$vol%]^d^"
