#!/bin/sh

test -s /home/fedepau/.config/dmenu/dmenurc && . home/fedepau/.config/dmenu/dmenurc

cmd="$(dmenu_path | dmenu "$@")"

case $cmd in
    *\!) "${TERMINAL:-st}" -e "${cmd%?}" & ;;
    *)   "${cmd}" & ;;
esac
